### ISSUE TITLE
 (This issue will be removed at 12am on 6 November)Solve November Long Challenge "Weapon Value"(SC31)

### ISSUE THREAD

**Issue by masterchef2209** [masterchef2209/GETSETFOSSCodingTasks#1]
https://www.codechef.com/NOV19B/problems/SC31

**Comment by lav-joshi** [comment]
im doing this

**Comment by yadavashu** [comment]
\\i am doing this

**Comment by Subhash2807** [comment]
i am doing this

**Comment by lav-joshi** [comment]
![Screenshot from 2019-11-03 19-35-55]
(https://user-images.githubusercontent.com/54629424/68086381-789faa00-fe71-11e9-9509-05e0b14e15ff.png)

**Comment by satyamlucifer** [comment]
i am working on it

**Comment by zeeshangengar1** [comment]
I am into it.

**Comment by Mrhb787** [comment]
// i would like to solve

**Comment by hellrider9** [comment]
I am doing this

**Comment by Punisher666** [comment]
i m working on it

**Comment by CharanpreetSingh056** [comment]
I want to solve this issue

**Comment by Yugraj124** [comment]
I am doing this

**Comment by meishansharma** [comment]
i am doing this

**Comment by dhananjayt365** [comment]
i am doing this.

**Comment by 0cirius0** [comment]
I am doing this

**Comment by harshitg00** [comment]
I am Working on this.

**Comment by anshul000777** [comment]
i am doing this

**Comment by masterchef2209** [comment]
1)Adding solution link is useless because submissions from a live contest are not accessible to other users.
2)Add only screenshot of your submissions page.
3)Upload screenshot rather than posting imgur links, as links may stop working later.

**Comment by dhananjayt365** [comment]
Sir but  how to share screenshot

**Comment by yk1ax** [comment]
i am working on this

**Comment by RohitKumar-200** [comment]
I am doing this

**Comment by MightyMoin** [comment]
i am doing this

**Comment by masterchef2209** [comment]
I will merge all pull requests in my free time. Thank you for your patience :)
PS: Do not send pull request from master branch, create a new branch make changes in it and send pull request from new branch.

**Comment by arhum602** [comment]
I am working on this..

**Comment by masterchef2209** [comment]
Some important instructions:-
1)Send pull requests from new branch, not from master branch of your fork.
2)DO NOT SEND SOLUTION CODE. For long challenge problems go to Problem->My Submissions->Take Screenshot->Send that as pull request.
3)Add screenshots inside the folder.

**Comment by 2110riya** [comment]
I'm doing this.

**Comment by Anikaagarwal10** [comment]
i want  to do this

**Comment by nirbhay55** [comment]
i am doing this

**Comment by akshatb622** [comment]
i am doing this

**Comment by feyre-2001** [comment]
I am doing this

**Comment by the-rdt** [comment]
i want ti try this

**Comment by ajagetia2001** [comment]
I am doing this

**Comment by mayank0811** [comment]
i am doing this.

**Comment by iamhritik55** [comment]
i am solving this.

**Comment by Mohit9486** [comment]
i solved this issue

**Comment by SeriousSam2622** [comment]
i am solving this

**Comment by ShivamMittal1802** [comment]
i am solving this

**Comment by masterchef2209** [comment]
This issue will be closed now, if you have already sent PR it will be merged.
