### ISSUE TITLE
 (This issue will be removed at 12am on 6 November)Solve November Long Challenge "Hard Sequence"(HRDSEQ)

### ISSUE THREAD

**Issue by masterchef2209** [masterchef2209/GETSETFOSSCodingTasks#2]
https://www.codechef.com/NOV19B/problems/HRDSEQ

**Comment by anshul000777** [comment]
i want to solve this issue.

**Comment by 1nsayn18** [comment]
I want to solve this issue

**Comment by CharanpreetSingh056** [comment]
I want to solve this issue

**Comment by 0cirius0** [comment]
I want to solve this

**Comment by blank-27** [comment]
i am claiming this issue

**Comment by GustavRamirez** [comment]
I want to solve this issue

**Comment by RohitKumar-200** [comment]
i want to solve this

**Comment by Mrhb787** [comment]
i would like to solve

**Comment by yk1ax** [comment]
I have opened a pull request for this issue

**Comment by arhum602** [comment]
i have opened a pull request for this

**Comment by meishansharma** [comment]
i would like to solve

**Comment by Punisher666** [comment]
i want to solve this issue

**Comment by 2110riya** [comment]
I'm claiming this issue.

**Comment by feyre-2001** [comment]
I am doing this.

**Comment by ajagetia2001** [comment]
i want to solve this

**Comment by MightyMoin** [comment]
i want to solve this

**Comment by SeriousSam2622** [comment]
I want to solve this

**Comment by masterchef2209** [comment]
This issue will be closed now, if you have already sent PR it will be merged.
