### ISSUE TITLE
Solve November Long Challenge "Physical Exercise"(PHCUL)

### ISSUE THREAD

**Issue by masterchef2209** [masterchef2209/GETSETFOSSCodingTasks#3]
https://www.codechef.com/NOV19B/problems/PHCUL

**Comment by 1nsayn18** [comment]
I want to solve this issue.

**Comment by anshul000777** [comment]
i want to solve this issue.

**Comment by 2110riya** [comment]
I'm claiming this issue.

**Comment by meishansharma** [comment]
i want to solve this issue

**Comment by yk1ax** [comment]
If my code gets half the test cases true, will I get any points at all

**Comment by masterchef2209** [comment]
> If my code gets half the test cases true, will I get any points at all

no, only on full solve. no points will be awarded on partial solve
