### ISSUE TITLE
Solve Painting Boxes

### ISSUE THREAD

**Issue by masterchef2209** [masterchef2209/GETSETFOSSCodingTasks#5]

**Comment by yadavashu** [comment]
//i want to do this issue.

**Comment by the-known-anon** [comment]
I want to solve this issue.

**Comment by Anikaagarwal10** [comment]
I want to solve this issue

**Comment by masterchef2209** [comment]
please go ahead, btw you only need to claim issues from debugging repository, you don't need to do it  in this repository, just send the pull request, the first to send valid pull request will get full points, rest everyone will get 5 points each, Good Luck :)

**Comment by lav-joshi** [comment]
where to go to claim issues 
where is debugging repo
and the option to pull request is not getting highlighted

**Comment by masterchef2209** [comment]
debugging repository(https://github.com/masterchef2209/GETSETFOSSDebuggingTasks) is another project. For this you just have to add the screenshot of accepted solution (your hackerrank  username should be visible) into the folder in this repo, and create a pull request.

**Comment by pawki07** [comment]
I want to solve this issue.

**Comment by meishansharma** [comment]
i want to solve this issue , my solution has been accepted on hackerrank

**Comment by masterchef2209** [comment]
> i want to solve this issue , my solution has been accepted on hackerrank

send pull request of screenshot of submission page

**Comment by meishansharma** [comment]
Sir i had send pull request for weapon value earlier.  Now i am clicking on
fork in painting boxes then adding screenshot then writing description and
then on commit changes
No pull request is being send
Sir can you please help

**Comment by masterchef2209** [comment]
Everyone passing test case #2 will get 5 points, there is some problem with test #1, I am investigating the issue. Sorry for inconvenience.

**Comment by masterchef2209** [comment]
There was some misunderstanding on my part, the question and test cases were correct. The question stilll has value of 15 points for first pull request, everyone who solve later will get 5 points each. Send pull request of your accepted verdict if you have already solved it(Do not send code).

**Comment by masterchef2209** [comment]
First valid PR for this problem was received from @pigmeister. Rest all will get 5 points on this problem from now on.

**Comment by masterchef2209** [comment]
There is a little change in language of problem statement. "adjacent" is replaced by "consecutive" to make the problem statement clearer

**Comment by ajagetia2001** [comment]
I want to solve this question

**Comment by Mohit9486** [comment]
i want to solve this question

**Comment by mayank0811** [comment]
i am solving this.

**Comment by Mohit9486** [comment]
i am having trouble opening this problem. I cannot find any link for it.

**Comment by ShivamMittal1802** [comment]
i have solved this issue

**Comment by dhananjayt365** [comment]
I want to solve this.

**Comment by iamhritik55** [comment]
i am solving this

**Comment by bajajvinamr** [comment]
#197  
solved
