### ISSUE TITLE
Everyone who partitipated in div3 #598 and doesn't satisfy requirements for issue #29 and #70 will get 5 points each :)

### ISSUE THREAD

**Issue by masterchef2209** [masterchef2209/GETSETFOSSCodingTasks#84]

**Comment by Retarded-Ape** [comment]
I Participated and got 5.4k rank.
Here is my profile [https://codeforces.com/profile/Retarded_Ape]
![Untitdfgdfhled](https://user-images.githubusercontent.com/56070571/68190842-393d9e80-ffd4-11e9-8112-28fec3773e76.png)

**Comment by masterchef2209** [comment]
@Retarded-Ape send screenshot of your position in standings as PR

**Comment by dhananjayt365** [comment]
I participated and got 5.6k rank
